### ISSUE TITLE
Populate Exposure Databases 

### ISSUE THREAD

**Issue by WillieDavonSmalls** [WillieDavonSmalls/ISH#21]
## Acceptance Criteria

[ ] The following tables: 
      cat_exposure, rdm_policy, catPP_Policies, CatPP_Programs, rms_accgrp, rms_policyconditioncriteria, rms_policyconditions, catPP_NM_GroundUpValues
[ ] Update Entity Framework Model

**Comment by zippy1981** [comment]
Fixed in #29
