### ISSUE TITLE
Things to install this weekend

### ISSUE THREAD

**Issue by zippy1981** [WillieDavonSmalls/ISH#44]
@WillieDavonSmalls please install the following on youre VM this weekend:

- [x] **Visual Studio 2017 15.3** Just go to `Tools|Extensions and Updates` and install any updates there are and then go to `Help | About` and make sure you end up on version 15.3

![image](https://user-images.githubusercontent.com/146930/30236582-8d7ea6ee-94ea-11e7-8e00-c0f586f4f121.png)

- [x] Command line version of GIT. We probably won't use it, but nice to have https://git-scm.com/download/win
- [x] [Visual Studio Code](https://code.visualstudio.com/docs/?dv=win) Nice to have. Probably won't touch.
- Update SSMS to the latest version. Help about should show you version 17

**Comment by WillieDavonSmalls** [comment]
Done.  Thanks, Justin.
